name: Test cat-which

on:
  push:
    branches: [main]
    paths:
      - 'bin/cat-which'
      - 'test/cat-which.bats'
      - 'lib/**'
      - 'sources/**'
  pull_request:
    branches: [main]
    paths:
      - 'bin/cat-which'
      - 'test/cat-which.bats'
      - 'lib/**'
      - 'sources/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Initialize submodules
        run: git submodule update --init --recursive
      - name: Run test
        run: |
          source ./source-all.sh
          ./lib/bats/bin/bats ./test/cat-which.bats
